import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'
import data from "../data/airRent"
import cardsData from "../data/cardsData"
import SmallCard from '../components/SmallCard'
import MediumCard from '../components/MediumCard'
import LargeCard from '../components/LargeCard'
import Footer from '../components/Footer'

export async function getStaticProps(){
  return{
    props:{
      data,
      cardsData
    }
  }
  
}

export default function Home({data,cardsData}) {
 
  return (
    <div className={styles.container}>
      <Head>
        <title>AirBnB by Daniel Emenike</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

  

      <Header/>

      <Banner/>
      <main className="max-w-7xl mx-auto px-8 sm:px-16">
      <section className='pt-6'>
        <h2 className="text-2xl font-semibold pb-5">Explore Nearby</h2>
      <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
        {data?.map((x)=>{
          return (
            <SmallCard key={x.id} img={x.img} location={x.location} distance={x.distance}/>
         
          
         )
        })}
        </div>
      </section>
      <div>
      
      </div>
        <section>
        <h2 className='text-2xl font-semibold py-6'>Live Anywhere </h2>
        <div className='flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3'>
        {cardsData.map((x)=>{
          return (
            <MediumCard key={x.id} img={x.img} title={x.title}/>
         
          
          
         )
        })}
        </div>
        </section>
      
        <LargeCard title="Cozy Indoor"
        description="Wishlists curated by AirBnB"
        buttonText="Get Inspired"
        img="/displayHouses/footer.jpg"
        />
      </main>

     <Footer />
    
    </div>
  )
}
